;;; dracula-purple-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme dracula-purple-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#362a3f")
  (shade2 "#49335c")
  (shade3 "#5d3b79")
  (shade4 "#704497")
  (shade5 "#844cb4")
  (shade6 "#9755d1")
  (shade7 "#ab5dee")
  (accent0 "#ab5dee")
  (accent1 "#ab5dee")
  (accent2 "#ab5dee")
  (accent3 "#ab5dee")
  (accent4 "#ab5dee")
  (accent5 "#ab5dee")
  (accent6 "#ab5dee")
  (accent7 "#ab5dee"))
(custom-theme-set-faces
  'dracula-purple-dark
<<20210601221052630320600>>

(provide-theme 'dracula-purple-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; dracula-purple-dark-theme.el ends here
