;;; dracula-purple-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme dracula-purple-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ab5dee")
  (shade1 "#9755d1")
  (shade2 "#844cb4")
  (shade3 "#704497")
  (shade4 "#5d3b79")
  (shade5 "#49335c")
  (shade6 "#362a3f")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'dracula-purple-light
<<20210601221052630320600>>

(provide-theme 'dracula-purple-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; dracula-purple-light-theme.el ends here
