;;; dracula-orange-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme dracula-orange-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ffb86c")
  (shade1 "#dfa361")
  (shade2 "#c08d57")
  (shade3 "#a0784c")
  (shade4 "#816242")
  (shade5 "#614d37")
  (shade6 "#42372d")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'dracula-orange-light
<<20210601221052630320600>>

(provide-theme 'dracula-orange-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; dracula-orange-light-theme.el ends here
