;;; dracula-orange-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme dracula-orange-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#42372d")
  (shade2 "#614d37")
  (shade3 "#816242")
  (shade4 "#a0784c")
  (shade5 "#c08d57")
  (shade6 "#dfa361")
  (shade7 "#ffb86c")
  (accent0 "#ffb86c")
  (accent1 "#ffb86c")
  (accent2 "#ffb86c")
  (accent3 "#ffb86c")
  (accent4 "#ffb86c")
  (accent5 "#ffb86c")
  (accent6 "#ffb86c")
  (accent7 "#ffb86c"))
(custom-theme-set-faces
  'dracula-orange-dark
<<20210601221052630320600>>

(provide-theme 'dracula-orange-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; dracula-orange-dark-theme.el ends here
