;;; exo-ui-red-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme exo-ui-red-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ff5156")
  (shade1 "#df4a4f")
  (shade2 "#c04447")
  (shade3 "#a03d40")
  (shade4 "#813638")
  (shade5 "#612f31")
  (shade6 "#422929")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'exo-ui-red-light
<<20210601221052630320600>>

(provide-theme 'exo-ui-red-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; exo-ui-red-light-theme.el ends here
