;;; exo-ui-red-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme exo-ui-red-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#422929")
  (shade2 "#612f31")
  (shade3 "#813638")
  (shade4 "#a03d40")
  (shade5 "#c04447")
  (shade6 "#df4a4f")
  (shade7 "#ff5156")
  (accent0 "#ff5156")
  (accent1 "#ff5156")
  (accent2 "#ff5156")
  (accent3 "#ff5156")
  (accent4 "#ff5156")
  (accent5 "#ff5156")
  (accent6 "#ff5156")
  (accent7 "#ff5156"))
(custom-theme-set-faces
  'exo-ui-red-dark
<<20210601221052630320600>>

(provide-theme 'exo-ui-red-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; exo-ui-red-dark-theme.el ends here
