;;; flamingo-pink-purple-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme flamingo-pink-purple-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ab5dee")
  (shade1 "#b768e0")
  (shade2 "#c272d3")
  (shade3 "#ce7dc5")
  (shade4 "#d987b7")
  (shade5 "#e592a9")
  (shade6 "#f09c9c")
  (shade7 "#fca78e")
  (accent0 "#fca78e")
  (accent1 "#fca78e")
  (accent2 "#fca78e")
  (accent3 "#fca78e")
  (accent4 "#fca78e")
  (accent5 "#fca78e")
  (accent6 "#fca78e")
  (accent7 "#fca78e"))
(custom-theme-set-faces
  'flamingo-pink-purple-dark
<<20210601221052630320600>>

(provide-theme 'flamingo-pink-purple-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; flamingo-pink-purple-dark-theme.el ends here
