;;; flamingo-pink-purple-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme flamingo-pink-purple-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#fca78e")
  (shade1 "#f09c9c")
  (shade2 "#e592a9")
  (shade3 "#d987b7")
  (shade4 "#ce7dc5")
  (shade5 "#c272d3")
  (shade6 "#b768e0")
  (shade7 "#ab5dee")
  (accent0 "#ab5dee")
  (accent1 "#ab5dee")
  (accent2 "#ab5dee")
  (accent3 "#ab5dee")
  (accent4 "#ab5dee")
  (accent5 "#ab5dee")
  (accent6 "#ab5dee")
  (accent7 "#ab5dee"))
(custom-theme-set-faces
  'flamingo-pink-purple-light
<<20210601221052630320600>>

(provide-theme 'flamingo-pink-purple-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; flamingo-pink-purple-light-theme.el ends here
