;;; ghostfreak-green-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme ghostfreak-green-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#e3ffc5")
  (shade1 "#c7dfae")
  (shade2 "#acc096")
  (shade3 "#90a07f")
  (shade4 "#758168")
  (shade5 "#596151")
  (shade6 "#3e4239")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'ghostfreak-green-light
<<20210601221052630320600>>

(provide-theme 'ghostfreak-green-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; ghostfreak-green-light-theme.el ends here
