;;; ghostfreak-green-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme ghostfreak-green-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#3e4239")
  (shade2 "#596151")
  (shade3 "#758168")
  (shade4 "#90a07f")
  (shade5 "#acc096")
  (shade6 "#c7dfae")
  (shade7 "#e3ffc5")
  (accent0 "#e3ffc5")
  (accent1 "#e3ffc5")
  (accent2 "#e3ffc5")
  (accent3 "#e3ffc5")
  (accent4 "#e3ffc5")
  (accent5 "#e3ffc5")
  (accent6 "#e3ffc5")
  (accent7 "#e3ffc5"))
(custom-theme-set-faces
  'ghostfreak-green-dark
<<20210601221052630320600>>

(provide-theme 'ghostfreak-green-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; ghostfreak-green-dark-theme.el ends here
