;;; herschel-flamingo-pink-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme herschel-flamingo-pink-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#413531")
  (shade2 "#604841")
  (shade3 "#7f5b50")
  (shade4 "#9f6e60")
  (shade5 "#be816f")
  (shade6 "#dd947f")
  (shade7 "#fca78e")
  (accent0 "#fca78e")
  (accent1 "#fca78e")
  (accent2 "#fca78e")
  (accent3 "#fca78e")
  (accent4 "#fca78e")
  (accent5 "#fca78e")
  (accent6 "#fca78e")
  (accent7 "#fca78e"))
(custom-theme-set-faces
  'herschel-flamingo-pink-dark
<<20210601221052630320600>>

(provide-theme 'herschel-flamingo-pink-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; herschel-flamingo-pink-dark-theme.el ends here
