;;; herschel-flamingo-pink-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme herschel-flamingo-pink-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#fca78e")
  (shade1 "#dd947f")
  (shade2 "#be816f")
  (shade3 "#9f6e60")
  (shade4 "#7f5b50")
  (shade5 "#604841")
  (shade6 "#413531")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'herschel-flamingo-pink-light
<<20210601221052630320600>>

(provide-theme 'herschel-flamingo-pink-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; herschel-flamingo-pink-light-theme.el ends here
