;;; lio-fotia-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme lio-fotia-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#a06088")
  (shade1 "#a6728d")
  (shade2 "#ab8591")
  (shade3 "#b19796")
  (shade4 "#b7a99a")
  (shade5 "#bdbb9f")
  (shade6 "#c2cea3")
  (shade7 "#c8e0a8")
  (accent0 "#c8e0a8")
  (accent1 "#c8e0a8")
  (accent2 "#c8e0a8")
  (accent3 "#c8e0a8")
  (accent4 "#c8e0a8")
  (accent5 "#c8e0a8")
  (accent6 "#c8e0a8")
  (accent7 "#c8e0a8"))
(custom-theme-set-faces
  'lio-fotia-dark
<<20210601221052630320600>>

(provide-theme 'lio-fotia-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; lio-fotia-dark-theme.el ends here
