;;; lio-fotia-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme lio-fotia-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#c8e0a8")
  (shade1 "#c2cea3")
  (shade2 "#bdbb9f")
  (shade3 "#b7a99a")
  (shade4 "#b19796")
  (shade5 "#ab8591")
  (shade6 "#a6728d")
  (shade7 "#a06088")
  (accent0 "#a06088")
  (accent1 "#a06088")
  (accent2 "#a06088")
  (accent3 "#a06088")
  (accent4 "#a06088")
  (accent5 "#a06088")
  (accent6 "#a06088")
  (accent7 "#a06088"))
(custom-theme-set-faces
  'lio-fotia-light
<<20210601221052630320600>>

(provide-theme 'lio-fotia-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; lio-fotia-light-theme.el ends here
