;;; orange-purple-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme orange-purple-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ffb86c")
  (shade1 "#f3ab7f")
  (shade2 "#e79e91")
  (shade3 "#db91a4")
  (shade4 "#cf84b6")
  (shade5 "#c377c9")
  (shade6 "#b76adb")
  (shade7 "#ab5dee")
  (accent0 "#ab5dee")
  (accent1 "#ab5dee")
  (accent2 "#ab5dee")
  (accent3 "#ab5dee")
  (accent4 "#ab5dee")
  (accent5 "#ab5dee")
  (accent6 "#ab5dee")
  (accent7 "#ab5dee"))
(custom-theme-set-faces
  'orange-purple-light
<<20210601221052630320600>>

(provide-theme 'orange-purple-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; orange-purple-light-theme.el ends here
