;;; orange-purple-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme orange-purple-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#ab5dee")
  (shade1 "#b76adb")
  (shade2 "#c377c9")
  (shade3 "#cf84b6")
  (shade4 "#db91a4")
  (shade5 "#e79e91")
  (shade6 "#f3ab7f")
  (shade7 "#ffb86c")
  (accent0 "#ffb86c")
  (accent1 "#ffb86c")
  (accent2 "#ffb86c")
  (accent3 "#ffb86c")
  (accent4 "#ffb86c")
  (accent5 "#ffb86c")
  (accent6 "#ffb86c")
  (accent7 "#ffb86c"))
(custom-theme-set-faces
  'orange-purple-dark
<<20210601221052630320600>>

(provide-theme 'orange-purple-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; orange-purple-dark-theme.el ends here
