;;; st-giles-blue-light-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme st-giles-blue-light)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#599ec4")
  (shade1 "#518cad")
  (shade2 "#497b96")
  (shade3 "#41697f")
  (shade4 "#3a5767")
  (shade5 "#324550")
  (shade6 "#2a3439")
  (shade7 "#222222")
  (accent0 "#222222")
  (accent1 "#222222")
  (accent2 "#222222")
  (accent3 "#222222")
  (accent4 "#222222")
  (accent5 "#222222")
  (accent6 "#222222")
  (accent7 "#222222"))
(custom-theme-set-faces
  'st-giles-blue-light
<<20210601221052630320600>>

(provide-theme 'st-giles-blue-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; st-giles-blue-light-theme.el ends here
