;;; st-giles-blue-dark-theme.el

;; Version: 1.0.1
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;; Generated by the emacs theme template for themer.

;;; Code:

(deftheme st-giles-blue-dark)
(let ((class '((class color) (min-colors 89)))
  (shade0 "#222222")
  (shade1 "#2a3439")
  (shade2 "#324550")
  (shade3 "#3a5767")
  (shade4 "#41697f")
  (shade5 "#497b96")
  (shade6 "#518cad")
  (shade7 "#599ec4")
  (accent0 "#599ec4")
  (accent1 "#599ec4")
  (accent2 "#599ec4")
  (accent3 "#599ec4")
  (accent4 "#599ec4")
  (accent5 "#599ec4")
  (accent6 "#599ec4")
  (accent7 "#599ec4"))
(custom-theme-set-faces
  'st-giles-blue-dark
<<20210601221052630320600>>

(provide-theme 'st-giles-blue-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; st-giles-blue-dark-theme.el ends here
